name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*' # Trigger on tags that start with 'v'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: docker_build
        run: |
          docker build \
            --file Dockerfile \
            --tag ${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }} \
            .

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }}
