name: Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Git Information
        id: git_info
        run: echo "::set-output name=commit_sha::$(git rev-parse --short HEAD)"

      - name: Set Date Timestamp
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Set Semantic Version
        id: semver
        run: echo "::set-output name=semver::$(cat pom.xml | grep '<version>' | head -n1 | sed 's/.*<version>\(.*\)<\/version>.*/\1/')"

      - name: Generate Version Information
        id: version
        run: echo "::set-output name=version::$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)"

      - name: Show Version
        run: | 
          echo "git_info is ${{ steps.git_info.outputs.commit_sha }}"
          echo "date is ${{ steps.date.outputs.date }}"
          echo "semver is ${{ steps.semver.outputs.semver }}"
          echo "version is ${{ steps.version.outputs.version }}"

      - name: Build Docker image
        run: |
          docker build --build-arg VERSION=${{ steps.semver.outputs.semver }} --build-arg DATE_TIMESTAMP=${{ steps.date.outputs.date }}" -t abhishekshinde/abhi:${{ github.sha }}-${{ steps.semver.outputs.semver }} .
          docker tag abhishekshinde/abhi:${{ github.sha }}-${{ steps.semver.outputs.semver }} abhishekshinde/abhi:latest
          docker tag abhishekshinde/abhi:${{ github.sha }}-${{ steps.semver.outputs.semver }} abhishekshinde/abhi:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Push Docker image
        run: |
          docker push abhishekshinde/abhi:${{ github.sha }}-${{ steps.semver.outputs.version }}
          docker push abhishekshinde/abhi:latest
          docker push abhishekshinde/abhi:${{ github.sha }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.semver }}
          release_name: Release ${{ steps.semver.outputs.semver }}
          body: |
            Release ${{ steps.semver.outputs.semver }}
          draft: false
          prerelease: false
